[build]
  base = "client"
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  functions = "client/netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
